{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "aks-demo.fullname" . }}
  labels:
    {{- include "aks-demo.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "aks-demo.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
      - containerName: api
        minAllowed:
          {{- toYaml .Values.vpa.minAllowed | nindent 10 }}
        maxAllowed:
          {{- toYaml .Values.vpa.maxAllowed | nindent 10 }}
        controlledResources:
          {{- toYaml .Values.vpa.controlledResources | nindent 10 }}
{{- end }}
